FEAT-> option to have meta (custom data)
mchev/banhammer pull request #3
Opened 2023-02-27 23:12 UTC by mepsd

2023-02-28 11:31 UTC, mchev requested changes
- The `metas` field in db should be in a new migration to allow package upgrades.
- In Ban.php, missing `use Illuminate\Database\Eloquent\Builder;`
- in Bannable.php, the scopeMeta method could be ambiguous. May be we should name it `scopeBansMeta` or even better `scopeWhereBansMeta` ?

2023-02-28 14:04 UTC, mepsd commented
Hey @mchev thanks for recommending the changes.
1. metas field moved to new file
2. In Ban.php, missing use Illuminate\Database\Eloquent\Builder; i cat see Builder there
3. Bannable.php rename the scope i like that idea renamed scope to scopeWhereBansMeta

Thank you!

2023-03-02 09:57 UTC, mepsd commented
@mchev any update?

2023-03-02 13:45 UTC, mepsd commented
- In the new migration, the table name should be config('ban.table') -> fIxed
- In Ban.php line 75 for the scopeMeta(), you use Builder so it should be imported Builder is already imported at line 6
- https://github.com/mepsd/banhammer/blob/0000000000000000000000000000000000000000:/src/Models/Ban.php#L6

Thank you!

2023-03-02 14:57 UTC, mchev approved these changes

2023-03-02 16:43 UTC, mchev commented on src/Models/Ban.php
> +    public function scopeMeta(Builder $query, string $name, $value): void
`scopeWhereMeta()`

2023-03-02 17:20 UTC, merged

2023-03-02 18:53 UTC, mchev commented on src/Models/Ban.php
> +    public function scopeMeta(Builder $query, string $name, $value): void
Since this method use `whereJsonContains`, the `whereMeta` make sense to me. I already edited this and added doc and test for these feature.